version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
      - ./static:/app/static
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db